source 'https://rubygems.org'
ruby '2.6.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'#, '4.2.5'
gem 'bootstrap-sass'#, '3.3.7'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3', '~> 1.3.7' 
gem 'pg'#, '~> 0.20'
# Use Haml for html abstraction
gem 'haml'
# Use SCSS for stylesheets
gem 'sass-rails'#, '~> 5.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'#, '>= 2.7.1'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'#, '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'#, '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc'#, '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt'#, '~> 3.1.7'

gem 'net-ssh'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# gem 'recaptcha'

gem 'haml'
gem 'social-share-button'#, '~> 0.1.6'

# Use for admin
gem 'rails_admin', '~> 1.3'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'factory_bot_rails', '~> 4.10.0'
  gem 'faker'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console'#, '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # for Heroku deployment - as described in Ap. A of ELLS book
  gem 'database_cleaner'#, '1.4.1'
  gem 'capybara'#, '2.4.4'
  gem 'launchy'
  gem 'rspec-rails'#, '3.7.2'
  gem 'ZenTest'
end


group :test do
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'
  gem 'simplecov', :require => false
end

# group :production do
#   gem 'pg'#,'0.20'
# end
